/***** Globals.h *****/

#pragma once

#define MAX_POLYPHONY 5
#define MAX_MODULES 8
#define MAX_PATCH_CABLES 100
#define MAX_MODULE_INPUTS 4
#define MAX_MODULE_OUTPUTS 4
#define MAX_MODULE_ANALOGS 4
#define MAX_MODULE_COMPONENT_SETS 8
#define MAX_COMPONENT_INPUTS 4
#define MAX_COMPONENT_OUTPUTS 4

// module types
#define MAIN_MODULE 1
#define SINE_MODULE 2
#define LFO_MODULE 3
#define RPS_MODULE 4
#define VCA_MODULE 5
#define ADSR_MODULE 6
#define FILTER_MODULE 7

// component types
#define PASS_THROUGH_COMPONENT 1
#define MIXER_COMPONENT 2
#define SINE_COMPONENT 3
#define LFO_COMPONENT 4
#define RPS_COMPONENT 5
#define DC_COMPONENT 6
#define VCA_COMPONENT 7
#define ADSR_COMPONENT 8
#define FILTER_COMPONENT 9
