/***** Globals.h *****/

#pragma once

#define MAX_POLYPHONY 6
#define MAX_MODULES 8
#define MAX_PATCH_CABLES 100
#define MAX_MODULE_INPUTS 4
#define MAX_MODULE_OUTPUTS 4
#define MAX_MODULE_ANALOGS 4
#define MAX_MODULE_COMPONENT_SETS 8
#define MAX_COMPONENT_INPUTS 4
#define MAX_COMPONENT_OUTPUTS 4
